-- Enable RLS
ALTER TABLE IF EXISTS public.cameras ENABLE ROW LEVEL SECURITY;

-- 1. Reference Tables
CREATE TABLE public.brands (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.series (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  brand_id bigint REFERENCES public.brands(id) ON DELETE CASCADE,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(name, brand_id)
);

CREATE TABLE public.colors (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  hex_code text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.conditions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  description text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.specialties (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Main Cameras Table
CREATE TABLE public.cameras (
  id bigint PRIMARY KEY, -- We'll preserve the IDs from data.js
  name text NOT NULL,
  brand_id bigint REFERENCES public.brands(id),
  series_id bigint REFERENCES public.series(id),
  category_id bigint REFERENCES public.categories(id),
  image text,
  images text[],
  specs jsonb,
  content jsonb,
  rental jsonb, -- Storing rental options as JSONB for simplicity (duration, price lists)
  features text[], -- Keeping features as an array for now
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Junction Tables
CREATE TABLE public.cameras_specialties (
  camera_id bigint REFERENCES public.cameras(id) ON DELETE CASCADE,
  specialty_id bigint REFERENCES public.specialties(id) ON DELETE CASCADE,
  PRIMARY KEY (camera_id, specialty_id)
);

CREATE TABLE public.camera_variants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  camera_id bigint REFERENCES public.cameras(id) ON DELETE CASCADE,
  condition_id bigint REFERENCES public.conditions(id),
  color_id bigint REFERENCES public.colors(id),
  price numeric,
  in_stock boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Featured/Hot Trends Table (New)
CREATE TABLE public.featured_cameras (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  camera_id bigint REFERENCES public.cameras(id) ON DELETE CASCADE,
  label text, -- e.g. "Hot Trend", "Best Seller"
  description text, -- Marketing copy
  features text[], -- Highlight features for the card
  display_order int DEFAULT 0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4b. Banners Table (New)
CREATE TABLE public.banners (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image text NOT NULL,
  link text,
  display_order int DEFAULT 0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- 5. RLS Policies
ALTER TABLE public.brands ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.series ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.colors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conditions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.specialties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cameras_specialties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.camera_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.featured_cameras ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.banners ENABLE ROW LEVEL SECURITY;

-- Allow full access for all (Dev Mode) - Replaces previous SELECT-only policies
DROP POLICY IF EXISTS "Allow public read access brands" ON public.brands;
CREATE POLICY "Enable all access for brands" ON public.brands FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read access categories" ON public.categories;
CREATE POLICY "Enable all access for categories" ON public.categories FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read access series" ON public.series;
CREATE POLICY "Enable all access for series" ON public.series FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read access colors" ON public.colors;
CREATE POLICY "Enable all access for colors" ON public.colors FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read access conditions" ON public.conditions;
CREATE POLICY "Enable all access for conditions" ON public.conditions FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read access specialties" ON public.specialties;
CREATE POLICY "Enable all access for specialties" ON public.specialties FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read access cameras" ON public.cameras;
CREATE POLICY "Enable all access for cameras" ON public.cameras FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read access cameras_specialties" ON public.cameras_specialties;
CREATE POLICY "Enable all access for cameras_specialties" ON public.cameras_specialties FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read access camera_variants" ON public.camera_variants;
CREATE POLICY "Enable all access for camera_variants" ON public.camera_variants FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read access featured_cameras" ON public.featured_cameras;
CREATE POLICY "Enable all access for featured_cameras" ON public.featured_cameras FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read access banners" ON public.banners;
CREATE POLICY "Enable all access for banners" ON public.banners FOR ALL USING (true) WITH CHECK (true);

-- 6. Storage
INSERT INTO storage.buckets (id, name, public) VALUES ('products', 'products', true) ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING ( bucket_id = 'products' );
CREATE POLICY "Allow uploads" ON storage.objects FOR INSERT WITH CHECK ( bucket_id = 'products' );

-- 7. Automated Storage Cleanup (Cascading Deletes for Images)
CREATE OR REPLACE FUNCTION public.delete_camera_files()
RETURNS TRIGGER AS $$
DECLARE
  url text;
  path text;
BEGIN
  -- 1. Handle Main Image
  IF OLD.image IS NOT NULL THEN
    -- Extract path: keeps everything after '/products/'
    path := substring(OLD.image FROM '/products/(.*)$');
    IF path IS NOT NULL THEN
      DELETE FROM storage.objects WHERE bucket_id = 'products' AND name = path;
    END IF;
  END IF;

  -- 2. Handle Gallery Images
  IF OLD.images IS NOT NULL THEN
    FOREACH url IN ARRAY OLD.images
    LOOP
      path := substring(url FROM '/products/(.*)$');
      IF path IS NOT NULL THEN
        DELETE FROM storage.objects WHERE bucket_id = 'products' AND name = path;
      END IF;
    END LOOP;
  END IF;

  RETURN OLD;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to run before a camera is deleted
DROP TRIGGER IF EXISTS on_camera_delete ON public.cameras;
CREATE TRIGGER on_camera_delete
  BEFORE DELETE ON public.cameras
  FOR EACH ROW EXECUTE FUNCTION public.delete_camera_files();
