-- Enable RLS
ALTER TABLE IF EXISTS public.cameras ENABLE ROW LEVEL SECURITY;

-- 1. Reference Tables
CREATE TABLE public.brands (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  image text,
  display_order int DEFAULT 0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.series (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  brand_id bigint REFERENCES public.brands(id) ON DELETE CASCADE,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(name, brand_id)
);

CREATE TABLE public.colors (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  hex_code text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.conditions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  description text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.specialties (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Main Cameras Table
CREATE TABLE public.cameras (
  id bigint PRIMARY KEY, -- We'll preserve the IDs from data.js
  name text NOT NULL,
  brand_id bigint REFERENCES public.brands(id),
  series_id bigint REFERENCES public.series(id),
  category_id bigint REFERENCES public.categories(id),
  image text,
  images text[],
  specs jsonb,
  content jsonb,
  rental jsonb, -- Storing rental options as JSONB for simplicity (duration, price lists)
  features text[], -- Keeping features as an array for now
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Junction Tables
CREATE TABLE public.cameras_specialties (
  camera_id bigint REFERENCES public.cameras(id) ON DELETE CASCADE,
  specialty_id bigint REFERENCES public.specialties(id) ON DELETE CASCADE,
  PRIMARY KEY (camera_id, specialty_id)
);

CREATE TABLE public.camera_variants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  camera_id bigint REFERENCES public.cameras(id) ON DELETE CASCADE,
  condition_id bigint REFERENCES public.conditions(id),
  color_id bigint REFERENCES public.colors(id),
  price numeric,
  in_stock boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Featured/Hot Trends Table (New)
CREATE TABLE public.featured_cameras (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  camera_id bigint REFERENCES public.cameras(id) ON DELETE CASCADE,
  label text, -- e.g. "Hot Trend", "Best Seller"
  description text, -- Marketing copy
  features text[], -- Highlight features for the card
  display_order int DEFAULT 0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4b. Banners Table (New)
CREATE TABLE public.banners (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image text NOT NULL,
  title text,
  description text,
  cta_text text,
  link text,
  display_order int DEFAULT 0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- 5. RLS Policies
ALTER TABLE public.brands ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.series ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.colors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conditions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.specialties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cameras_specialties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.camera_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.featured_cameras ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.banners ENABLE ROW LEVEL SECURITY;

-- Allow full access for all (Dev Mode) - Replaces previous SELECT-only policies
DROP POLICY IF EXISTS "Allow public read access brands" ON public.brands;
CREATE POLICY "Enable all access for brands" ON public.brands FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read access categories" ON public.categories;
CREATE POLICY "Enable all access for categories" ON public.categories FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read access series" ON public.series;
CREATE POLICY "Enable all access for series" ON public.series FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read access colors" ON public.colors;
CREATE POLICY "Enable all access for colors" ON public.colors FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read access conditions" ON public.conditions;
CREATE POLICY "Enable all access for conditions" ON public.conditions FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read access specialties" ON public.specialties;
CREATE POLICY "Enable all access for specialties" ON public.specialties FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read access cameras" ON public.cameras;
CREATE POLICY "Enable all access for cameras" ON public.cameras FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read access cameras_specialties" ON public.cameras_specialties;
CREATE POLICY "Enable all access for cameras_specialties" ON public.cameras_specialties FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read access camera_variants" ON public.camera_variants;
CREATE POLICY "Enable all access for camera_variants" ON public.camera_variants FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read access featured_cameras" ON public.featured_cameras;
CREATE POLICY "Enable all access for featured_cameras" ON public.featured_cameras FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read access banners" ON public.banners;
CREATE POLICY "Enable all access for banners" ON public.banners FOR ALL USING (true) WITH CHECK (true);

-- 6. Storage
INSERT INTO storage.buckets (id, name, public) VALUES ('products', 'products', true) ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING ( bucket_id = 'products' );
CREATE POLICY "Allow uploads" ON storage.objects FOR INSERT WITH CHECK ( bucket_id = 'products' );
CREATE POLICY "Allow public delete" ON storage.objects FOR DELETE USING ( bucket_id = 'products' );

-- 7. Automated Storage Cleanup (Cascading Deletes for Images)
CREATE OR REPLACE FUNCTION public.delete_camera_files()
RETURNS TRIGGER AS $$
DECLARE
  url text;
  path text;
BEGIN
  -- 1. Handle Main Image
  IF OLD.image IS NOT NULL THEN
    -- Extract path: keeps everything after '/products/'
    path := substring(OLD.image FROM '/products/(.*)$');
    IF path IS NOT NULL THEN
      DELETE FROM storage.objects WHERE bucket_id = 'products' AND name = path;
    END IF;
  END IF;

  -- 2. Handle Gallery Images
  IF OLD.images IS NOT NULL THEN
    FOREACH url IN ARRAY OLD.images
    LOOP
      path := substring(url FROM '/products/(.*)$');
      IF path IS NOT NULL THEN
        DELETE FROM storage.objects WHERE bucket_id = 'products' AND name = path;
      END IF;
    END LOOP;
  END IF;

  RETURN OLD;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to run before a camera is deleted
DROP TRIGGER IF EXISTS on_camera_delete ON public.cameras;
CREATE TRIGGER on_camera_delete
  BEFORE DELETE ON public.cameras
  FOR EACH ROW EXECUTE FUNCTION public.delete_camera_files();

-- Create Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name text NOT NULL,
  customer_contact text NOT NULL,
  customer_address text,
  customer_message text,
  camera_id bigint REFERENCES public.cameras(id),
  type text NOT NULL, -- 'RENT' or 'BUY'
  status text DEFAULT 'NEW', -- NEW, CONTACTED, COMPLETED, CANCELLED
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Policies
DROP POLICY IF EXISTS "Enable insert for everyone" ON public.orders;
CREATE POLICY "Enable insert for everyone" ON public.orders FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Enable read access for all" ON public.orders;
CREATE POLICY "Enable read access for all" ON public.orders FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable update for all" ON public.orders;
CREATE POLICY "Enable update for all" ON public.orders FOR UPDATE USING (true);

-- Enable Realtime
alter publication supabase_realtime add table public.orders;
-- Helper to check if user is admin (authenticated)
-- For simplicity, we assume any authenticated user is an admin in this context,
-- as we are disabling public sign-ups.

-- 1. CAMERAS Policy
ALTER TABLE public.cameras ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read Cameras" ON public.cameras;
CREATE POLICY "Public Read Cameras" ON public.cameras FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin All Cameras" ON public.cameras;
CREATE POLICY "Admin All Cameras" ON public.cameras FOR ALL USING (auth.role() = 'authenticated');


-- 2. CAMERA VARIANTS Policy
ALTER TABLE public.camera_variants ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read Variants" ON public.camera_variants;
CREATE POLICY "Public Read Variants" ON public.camera_variants FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin All Variants" ON public.camera_variants;
CREATE POLICY "Admin All Variants" ON public.camera_variants FOR ALL USING (auth.role() = 'authenticated');


-- 3. LOOKUP TABLES (Brands, Series, Categories, Conditions, Colors, Specialties)
-- Read: Public, Write: Admin

DO $$
DECLARE
    tables text[] := ARRAY['brands', 'series', 'categories', 'conditions', 'colors', 'specialties', 'cameras_specialties'];
    t text;
BEGIN
    FOREACH t IN ARRAY tables LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
        
        EXECUTE format('DROP POLICY IF EXISTS "Public Read %s" ON public.%I', t, t);
        EXECUTE format('CREATE POLICY "Public Read %s" ON public.%I FOR SELECT USING (true)', t, t);
        
        EXECUTE format('DROP POLICY IF EXISTS "Admin All %s" ON public.%I', t, t);
        EXECUTE format('CREATE POLICY "Admin All %s" ON public.%I FOR ALL USING (auth.role() = ''authenticated'')', t, t);
    END LOOP;
END $$;


-- 4. BANNERS Policy
ALTER TABLE public.banners ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read Banners" ON public.banners;
CREATE POLICY "Public Read Banners" ON public.banners FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin All Banners" ON public.banners;
CREATE POLICY "Admin All Banners" ON public.banners FOR ALL USING (auth.role() = 'authenticated');


-- 5. FEATURED_CAMERAS Policy
ALTER TABLE public.featured_cameras ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read Featured" ON public.featured_cameras;
CREATE POLICY "Public Read Featured" ON public.featured_cameras FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin All Featured" ON public.featured_cameras;
CREATE POLICY "Admin All Featured" ON public.featured_cameras FOR ALL USING (auth.role() = 'authenticated');


-- 6. ORDERS Policy
-- Insert: Public (Anonymous users need to create orders)
-- Select/Update/Delete: Admin Only (for now, unless users track own orders)

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable insert for everyone" ON public.orders;
CREATE POLICY "Public Insert Orders" ON public.orders FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Enable read access for all" ON public.orders;
DROP POLICY IF EXISTS "Enable update for all" ON public.orders;

DROP POLICY IF EXISTS "Admin Manage Orders" ON public.orders;
CREATE POLICY "Admin Manage Orders" ON public.orders FOR ALL USING (auth.role() = 'authenticated');

CREATE TABLE IF NOT EXISTS public.store_settings (
  id int PRIMARY KEY DEFAULT 1,
  brand_name text DEFAULT '4cats.camera',
  brand_description text,
  facebook_url text,
  instagram_url text,
  locations jsonb DEFAULT '[]',
  support_links jsonb DEFAULT '[]',
  contact_email text,
  contact_phones text[],
  opening_hours text,
  copyright_text text,
  CONSTRAINT single_row CHECK (id = 1)
);

-- Initial Data
INSERT INTO public.store_settings (
  id, brand_name, brand_description, facebook_url, instagram_url, 
  locations, support_links, contact_email, contact_phones, 
  opening_hours, copyright_text
) VALUES (
  1,
  '4cats.camera 📸',
  'Chuyên cung cấp các dòng máy ảnh Compact, Mirrorless, DSLR đã qua sử dụng với chất lượng tốt nhất. Uy tín tạo nên thương hiệu.',
  'https://www.facebook.com/profile.php?id=100093056073018',
  'https://www.instagram.com/4cats.camera/',
  '[{"name": "Cơ sở 1 - Cầu Giấy (CSKH & Bảo Hành)", "address": "Số 6A2, ngõ 158 Nguyễn Khánh Toàn, Quan Hoa, Cầu Giấy, Hà Nội", "iframe_url": "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3723.8481119837325!2d105.79822241030531!3d21.038762580532197!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3135ab3edc7bd19d%3A0xe62497f72909045d!2zNmEyIE5nLiAxNTggxJAuIE5ndXnhu4VuIEtow6FuaCBUb8OgbiwgUXVhbiBIb2EsIEPhuqd1IEdp4bqleSwgSMOgIE7hu5lpIDEwMDAwLCBWaWV0bmFt!5e0!3m2!1sen!2s!4v1770485061727!5m2!1sen!2s", "phone": "039 824 9856", "email": "fourcatscamera@gmail.com", "facebook": "https://www.facebook.com/profile.php?id=100093056073018", "zalo": "https://zalo.me/0398249856"}, {"name": "Cơ sở 2 - Thanh Xuân", "address": "Số 51 Nguyễn Trãi, Ngã tư Sở, Thanh Xuân, Hà Nội", "iframe_url": "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3724.7608510508912!2d105.81966159999999!3d21.0022214!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3135ac84fafbf469%3A0xbc58d65e5e48b023!2zNTEgxJAuIE5ndXnhu4VuIFRyw6NpLCBOZ8OjIFTGsCBT4bufLCBUaGFuaCBYdcOibiwgSMOgIE7hu5lpIDEwMDAwMCwgVmlldG5hbQ!5e0!3m2!1sen!2s!4v1770485168357!5m2!1sen!2s", "phone": "093 235 68 69", "email": "fourcatscamera@gmail.com", "facebook": "https://www.facebook.com/profile.php?id=100093056073018", "zalo": "https://zalo.me/0932356869"}]',
  '[{"label": "Chính sách bảo hành", "href": "#"}, {"label": "Chính sách đổi trả", "href": "#"}, {"label": "Hướng dẫn mua hàng", "href": "#"}, {"label": "Gửi yêu cầu bảo hành", "href": "#"}]',
  'fourcatscamera@gmail.com',
  ARRAY['039 824 9856', '093 235 68 69'],
  'Open: 9:00 - 21:00',
  '© 2026 4cats.camera - Người bạn đồng hành cùng đam mê nhiếp ảnh 🐱📸'
) ON CONFLICT (id) DO NOTHING;

-- Security Policies
ALTER TABLE public.store_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Settings" ON public.store_settings FOR SELECT USING (true);
CREATE POLICY "Admin Manage Settings" ON public.store_settings FOR ALL USING (auth.role() = 'authenticated');