-- ==============================================================================
-- 4cats Camera — Schema V3: Genuine Brand-New Camera E-Commerce Architecture
-- ==============================================================================
-- Architecture: PRODUCT (Model) -> PRODUCT VARIANTS / SKUs -> STOCK (Branch Level)
-- NO LONGER designed around used-camera condition %, shutter count, or cosmetic grade.
-- ==============================================================================

-- 1. EXTENSIONS & UUID
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. ENSURE CAMERAS TABLE HAS NEW CAMERA ARCHITECTURE COLUMNS
ALTER TABLE IF EXISTS public.cameras 
  ADD COLUMN IF NOT EXISTS slug text,
  ADD COLUMN IF NOT EXISTS short_description text,
  ADD COLUMN IF NOT EXISTS beginner_summary text,
  ADD COLUMN IF NOT EXISTS strengths text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS limitations text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS use_cases text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS technical_specs jsonb DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS compatible_accessories jsonb DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS search_aliases text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS is_published boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS is_featured boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS featured_section text DEFAULT 'featured',
  ADD COLUMN IF NOT EXISTS featured_order int DEFAULT 0,
  ADD COLUMN IF NOT EXISTS seo_title text,
  ADD COLUMN IF NOT EXISTS seo_description text,
  ADD COLUMN IF NOT EXISTS status text DEFAULT 'published',
  ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT timezone('utc'::text, now());

-- 3. ENSURE CAMERA_VARIANTS TABLE HAS SKU, PRICING & STOCK COLUMNS
ALTER TABLE IF EXISTS public.camera_variants
  ADD COLUMN IF NOT EXISTS sku text,
  ADD COLUMN IF NOT EXISTS color text,
  ADD COLUMN IF NOT EXISTS color_label text,
  ADD COLUMN IF NOT EXISTS color_hex text,
  ADD COLUMN IF NOT EXISTS kit_type text DEFAULT 'Body only',
  ADD COLUMN IF NOT EXISTS kit_label text DEFAULT 'Thân máy (Body only)',
  ADD COLUMN IF NOT EXISTS included_lens text,
  ADD COLUMN IF NOT EXISTS compare_at_price numeric,
  ADD COLUMN IF NOT EXISTS cost_price numeric,
  ADD COLUMN IF NOT EXISTS stock_quantity int DEFAULT 0,
  ADD COLUMN IF NOT EXISTS branch_stock jsonb DEFAULT '{"Cầu Giấy": 0, "Thanh Xuân": 0}',
  ADD COLUMN IF NOT EXISTS warranty text DEFAULT '12 tháng chính hãng',
  ADD COLUMN IF NOT EXISTS weight_grams int,
  ADD COLUMN IF NOT EXISTS variant_images text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS status text DEFAULT 'active';

-- 4. BANNERS TABLE ENHANCEMENTS FOR SCHEDULING & MOBILE
ALTER TABLE IF EXISTS public.banners
  ADD COLUMN IF NOT EXISTS internal_name text,
  ADD COLUMN IF NOT EXISTS subtitle text,
  ADD COLUMN IF NOT EXISTS mobile_image text,
  ADD COLUMN IF NOT EXISTS start_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS end_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS status text DEFAULT 'active';

-- 5. BRANCHES TABLE
CREATE TABLE IF NOT EXISTS public.branches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  short_name text NOT NULL,
  address text NOT NULL,
  phone text NOT NULL,
  zalo_url text,
  facebook_url text,
  opening_hours text DEFAULT '09:00 - 21:00',
  is_active boolean DEFAULT true,
  display_order int DEFAULT 0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Seed Default Branches if empty
INSERT INTO public.branches (name, short_name, address, phone, zalo_url, opening_hours, display_order)
VALUES 
  ('Cơ sở 1 - Cầu Giấy', 'Cầu Giấy', 'Số 6A2, ngõ 158 Nguyễn Khánh Toàn, Quan Hoa, Cầu Giấy, Hà Nội', '039 824 9856', 'https://zalo.me/0398249856', '09:00 - 21:00', 1),
  ('Cơ sở 2 - Thanh Xuân', 'Thanh Xuân', 'Số 51 Nguyễn Trãi, Ngã tư Sở, Thanh Xuân, Hà Nội', '093 235 68 69', 'https://zalo.me/0932356869', '09:00 - 21:00', 2)
ON CONFLICT DO NOTHING;

-- 6. STOCK MOVEMENTS AUDIT LOG
CREATE TABLE IF NOT EXISTS public.stock_movements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku text NOT NULL,
  camera_id bigint REFERENCES public.cameras(id) ON DELETE SET NULL,
  branch_name text NOT NULL,
  quantity_change int NOT NULL,
  quantity_after int NOT NULL,
  reason text NOT NULL,
  reference_order_id text,
  staff_email text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. PROMOTIONS / COUPONS TABLE
CREATE TABLE IF NOT EXISTS public.promotions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text UNIQUE,
  title text NOT NULL,
  customer_label text,
  description text,
  discount_type text NOT NULL DEFAULT 'percentage',
  discount_value numeric NOT NULL,
  min_order_value numeric DEFAULT 0,
  start_at timestamp with time zone,
  end_at timestamp with time zone,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. REDIRECTS (301 PERMANENT REDIRECTS FOR LEGACY URLS)
CREATE TABLE IF NOT EXISTS public.url_redirects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_path text NOT NULL UNIQUE,
  to_path text NOT NULL,
  status_code int DEFAULT 301,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Seed common legacy redirect examples
INSERT INTO public.url_redirects (from_path, to_path)
VALUES 
  ('/may-anh-cu/canon-r50', '/may-anh/canon-eos-r50'),
  ('/may-anh-cu/sony-zve10', '/may-anh/sony-zv-e10-ii'),
  ('/may-anh-cu/fujifilm-xt30', '/may-anh/fujifilm-x-t30-ii')
ON CONFLICT (from_path) DO NOTHING;

-- 9. FAQ TABLE
CREATE TABLE IF NOT EXISTS public.faqs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  camera_id bigint REFERENCES public.cameras(id) ON DELETE CASCADE,
  question text NOT NULL,
  answer text NOT NULL,
  display_order int DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 10. REVIEWS TABLE (MODERATED)
CREATE TABLE IF NOT EXISTS public.reviews (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  camera_id bigint REFERENCES public.cameras(id) ON DELETE CASCADE,
  customer_name text NOT NULL,
  customer_phone_masked text,
  rating int NOT NULL DEFAULT 5,
  comment text NOT NULL,
  status text DEFAULT 'approved',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 11. INDEXES
CREATE INDEX IF NOT EXISTS idx_cameras_slug ON public.cameras(slug);
CREATE INDEX IF NOT EXISTS idx_cameras_status ON public.cameras(status);
CREATE INDEX IF NOT EXISTS idx_camera_variants_sku ON public.camera_variants(sku);
CREATE INDEX IF NOT EXISTS idx_stock_movements_sku ON public.stock_movements(sku);
