-- ==============================================================================
-- 4cats Camera — Schema V2: Product Models & Used Inventory Units Architecture
-- ==============================================================================

-- 1. PRODUCT MODELS TABLE (General Camera Model Definition)
CREATE TABLE IF NOT EXISTS public.product_models (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  brand text NOT NULL,
  model_name text NOT NULL,
  series text,
  camera_type text NOT NULL DEFAULT 'Mirrorless', -- 'Mirrorless', 'Compact', 'DSLR'
  sensor_type text,                               -- 'APS-C', 'Full-Frame', '1.0-type', 'Micro 4/3'
  sensor_size text,
  megapixels text,
  lens_mount text,                                -- e.g. 'Canon RF', 'Sony E', 'Fujifilm X'
  compatible_native_mounts text[] DEFAULT '{}',   -- e.g. ARRAY['RF', 'RF-S']
  compatible_adapter_mounts text[] DEFAULT '{}',  -- e.g. ARRAY['EF', 'EF-S']
  video_capabilities text,
  screen_type text,
  weight text,
  ibis boolean DEFAULT false,
  viewfinder text,
  built_in_flash boolean DEFAULT false,
  wifi boolean DEFAULT true,
  bluetooth boolean DEFAULT true,
  mic_input boolean DEFAULT true,
  release_year int,
  short_description text,
  beginner_summary text,
  strengths text[] DEFAULT '{}',
  limitations text[] DEFAULT '{}',
  use_cases text[] DEFAULT '{}',                  -- e.g. ARRAY['Người mới', 'Selfie', 'Vlog', 'Du lịch']
  skill_levels text[] DEFAULT '{}',
  characteristics text[] DEFAULT '{}',
  technical_specs jsonb DEFAULT '{}',
  sample_images jsonb DEFAULT '[]',               -- array of { url, title, lens, settings }
  official_images text[] DEFAULT '{}',
  main_image text,
  seo_title text,
  seo_description text,
  is_published boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. INVENTORY UNITS TABLE (Individual Used Camera Inventory)
CREATE TABLE IF NOT EXISTS public.inventory_units (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_code text NOT NULL UNIQUE,                 -- e.g. 'R50-W01', 'XT30-S02'
  product_model_id bigint REFERENCES public.product_models(id) ON DELETE CASCADE,
  model_slug text NOT NULL,
  color text NOT NULL,                            -- 'White', 'Black', 'Silver', etc.
  condition_grade text NOT NULL,                  -- '99% — Like New', '98% — Rất đẹp', '95% — Đẹp'
  condition_percentage int NOT NULL DEFAULT 98,
  condition_summary text,
  shutter_count int,                              -- null if electronic shutter or unverified
  shutter_count_status text DEFAULT 'verified',   -- 'verified', 'not_applicable'
  is_kit boolean DEFAULT false,                   -- true if includes kit lens
  kit_lens_name text,                             -- e.g. 'RF-S 18-45mm F4.5-6.3 IS STM'
  cosmetic_notes text[] DEFAULT '{}',
  technical_notes text[] DEFAULT '{}',
  known_defects text[] DEFAULT '{}',
  included_accessories text[] DEFAULT '{}',       -- e.g. Pin zin, Sạc, Dây đeo, Nắp body, Box
  missing_accessories text[] DEFAULT '{}',        -- e.g. Thẻ nhớ, Hộp
  box_status text DEFAULT 'No box',               -- 'Full box', 'No box', 'Box trắng'
  price numeric NOT NULL,
  original_price numeric,
  branch_id int NOT NULL DEFAULT 1,               -- 1: Cầu Giấy, 2: Thanh Xuân
  branch_name text NOT NULL DEFAULT 'Cầu Giấy',
  stock_status text NOT NULL DEFAULT 'in_stock',  -- 'in_stock', 'reserved', 'sold', 'incoming', 'order_only', 'hidden'
  reservation_status text DEFAULT 'available',    -- 'available', 'reserved', 'expired'
  reservation_customer text,
  reservation_contact text,
  reserved_at timestamp with time zone,
  reservation_expires_at timestamp with time zone,
  warranty_months int DEFAULT 6,
  return_days int DEFAULT 7,
  inspection_date date DEFAULT CURRENT_DATE,
  inspection_staff text DEFAULT 'Team Kỹ thuật 4cats',
  inspection_checklist jsonb DEFAULT '{"sensor": true, "shutter": true, "autofocus": true, "buttons_dials": true, "lcd": true, "evf": true, "flash": true, "card_slot": true, "wifi_bluetooth": true, "ports": true, "battery_charging": true, "lens_mount_contacts": true}',
  actual_images text[] DEFAULT '{}',
  defect_images text[] DEFAULT '{}',
  test_video_url text,
  serial_number_masked text,                      -- e.g. '2340*****89'
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  sold_at timestamp with time zone
);

-- 3. INDEXES FOR HIGH-PERFORMANCE SEARCH & FILTERING
CREATE INDEX IF NOT EXISTS idx_product_models_slug ON public.product_models(slug);
CREATE INDEX IF NOT EXISTS idx_product_models_brand ON public.product_models(brand);
CREATE INDEX IF NOT EXISTS idx_inventory_units_model_id ON public.inventory_units(product_model_id);
CREATE INDEX IF NOT EXISTS idx_inventory_units_model_slug ON public.inventory_units(model_slug);
CREATE INDEX IF NOT EXISTS idx_inventory_units_unit_code ON public.inventory_units(unit_code);
CREATE INDEX IF NOT EXISTS idx_inventory_units_stock_status ON public.inventory_units(stock_status);
CREATE INDEX IF NOT EXISTS idx_inventory_units_branch_id ON public.inventory_units(branch_id);

-- 4. ROW LEVEL SECURITY (RLS) POLICIES
ALTER TABLE public.product_models ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_units ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read Product Models" ON public.product_models;
CREATE POLICY "Public Read Product Models" ON public.product_models FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin Manage Product Models" ON public.product_models;
CREATE POLICY "Admin Manage Product Models" ON public.product_models FOR ALL USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Public Read Inventory Units" ON public.inventory_units;
CREATE POLICY "Public Read Inventory Units" ON public.inventory_units FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin Manage Inventory Units" ON public.inventory_units;
CREATE POLICY "Admin Manage Inventory Units" ON public.inventory_units FOR ALL USING (auth.role() = 'authenticated');

-- Enable Realtime
alter publication supabase_realtime add table public.inventory_units;
