-- ==============================================================================
-- 4cats Camera — Supabase Database Migration
-- Genuine Brand-New Camera E-Commerce Architecture (Single Source of Truth)
-- ==============================================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. ENSURE CAMERAS TABLE HAS COMPREHENSIVE PRODUCT COLUMNS
ALTER TABLE IF EXISTS public.cameras 
  ADD COLUMN IF NOT EXISTS slug text,
  ADD COLUMN IF NOT EXISTS short_description text,
  ADD COLUMN IF NOT EXISTS beginner_summary text,
  ADD COLUMN IF NOT EXISTS price numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sale_price numeric,
  ADD COLUMN IF NOT EXISTS stock_quantity int DEFAULT 0,
  ADD COLUMN IF NOT EXISTS status text DEFAULT 'published',
  ADD COLUMN IF NOT EXISTS is_published boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS is_featured boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS featured_section text DEFAULT 'featured',
  ADD COLUMN IF NOT EXISTS featured_order int DEFAULT 0,
  ADD COLUMN IF NOT EXISTS strengths text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS limitations text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS use_cases text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS technical_specs jsonb DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS compatible_accessories jsonb DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS search_aliases text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS seo_title text,
  ADD COLUMN IF NOT EXISTS seo_description text,
  ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT timezone('utc'::text, now());

-- 3. ENSURE CAMERA_VARIANTS TABLE HAS SKU, PRICING & STOCK COLUMNS
ALTER TABLE IF EXISTS public.camera_variants
  ADD COLUMN IF NOT EXISTS sku text,
  ADD COLUMN IF NOT EXISTS color text,
  ADD COLUMN IF NOT EXISTS color_label text,
  ADD COLUMN IF NOT EXISTS color_hex text,
  ADD COLUMN IF NOT EXISTS kit_type text DEFAULT 'Body only',
  ADD COLUMN IF NOT EXISTS kit_label text DEFAULT 'Thân máy (Body only)',
  ADD COLUMN IF NOT EXISTS included_lens text,
  ADD COLUMN IF NOT EXISTS compare_at_price numeric,
  ADD COLUMN IF NOT EXISTS cost_price numeric,
  ADD COLUMN IF NOT EXISTS stock_quantity int DEFAULT 0,
  ADD COLUMN IF NOT EXISTS branch_stock jsonb DEFAULT '{"Cầu Giấy": 0, "Thanh Xuân": 0}',
  ADD COLUMN IF NOT EXISTS warranty text DEFAULT '12 tháng chính hãng',
  ADD COLUMN IF NOT EXISTS weight_grams int,
  ADD COLUMN IF NOT EXISTS variant_images text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS status text DEFAULT 'active';

-- 4. BANNERS TABLE ENHANCEMENTS
ALTER TABLE IF EXISTS public.banners
  ADD COLUMN IF NOT EXISTS internal_name text,
  ADD COLUMN IF NOT EXISTS subtitle text,
  ADD COLUMN IF NOT EXISTS mobile_image text,
  ADD COLUMN IF NOT EXISTS start_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS end_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS status text DEFAULT 'active';

-- 5. BRANCHES TABLE
CREATE TABLE IF NOT EXISTS public.branches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  short_name text NOT NULL,
  address text NOT NULL,
  phone text NOT NULL,
  zalo_url text,
  facebook_url text,
  opening_hours text DEFAULT '09:00 - 21:00',
  is_active boolean DEFAULT true,
  display_order int DEFAULT 0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Seed Branches if empty
INSERT INTO public.branches (name, short_name, address, phone, zalo_url, opening_hours, display_order)
VALUES 
  ('Cơ sở 1 - Cầu Giấy', 'Cầu Giấy', 'Số 6A2, ngõ 158 Nguyễn Khánh Toàn, Quan Hoa, Cầu Giấy, Hà Nội', '039 824 9856', 'https://zalo.me/0398249856', '09:00 - 21:00', 1),
  ('Cơ sở 2 - Thanh Xuân', 'Thanh Xuân', 'Số 51 Nguyễn Trãi, Ngã tư Sở, Thanh Xuân, Hà Nội', '093 235 68 69', 'https://zalo.me/0932356869', '09:00 - 21:00', 2)
ON CONFLICT DO NOTHING;

-- 6. STOCK MOVEMENTS AUDIT LOG
CREATE TABLE IF NOT EXISTS public.stock_movements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku text NOT NULL,
  camera_id bigint REFERENCES public.cameras(id) ON DELETE SET NULL,
  branch_name text NOT NULL,
  quantity_change int NOT NULL,
  quantity_after int NOT NULL,
  reason text NOT NULL,
  reference_order_id text,
  staff_email text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. PROMOTIONS TABLE
CREATE TABLE IF NOT EXISTS public.promotions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text UNIQUE,
  title text NOT NULL,
  customer_label text,
  description text,
  discount_type text NOT NULL DEFAULT 'percentage',
  discount_value numeric NOT NULL,
  min_order_value numeric DEFAULT 0,
  start_at timestamp with time zone,
  end_at timestamp with time zone,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. REDIRECTS TABLE (For SEO preservation)
CREATE TABLE IF NOT EXISTS public.url_redirects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_path text NOT NULL UNIQUE,
  to_path text NOT NULL,
  status_code int DEFAULT 301,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 9. PERFORMANCE INDEXES
CREATE INDEX IF NOT EXISTS idx_cameras_slug ON public.cameras(slug);
CREATE INDEX IF NOT EXISTS idx_cameras_status ON public.cameras(status);
CREATE INDEX IF NOT EXISTS idx_cameras_is_published ON public.cameras(is_published);
CREATE INDEX IF NOT EXISTS idx_cameras_is_featured ON public.cameras(is_featured);
CREATE INDEX IF NOT EXISTS idx_cameras_brand_id ON public.cameras(brand_id);
CREATE INDEX IF NOT EXISTS idx_camera_variants_sku ON public.camera_variants(sku);
CREATE INDEX IF NOT EXISTS idx_camera_variants_camera_id ON public.camera_variants(camera_id);
CREATE INDEX IF NOT EXISTS idx_banners_display_order ON public.banners(display_order);

-- 10. ROW LEVEL SECURITY (RLS) POLICIES
ALTER TABLE public.cameras ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.camera_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.brands ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.series ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.banners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promotions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.store_settings ENABLE ROW LEVEL SECURITY;

-- Public can read published cameras and active metadata
DROP POLICY IF EXISTS "Public can view cameras" ON public.cameras;
CREATE POLICY "Public can view cameras" ON public.cameras FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public can view camera variants" ON public.camera_variants;
CREATE POLICY "Public can view camera variants" ON public.camera_variants FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public can view brands" ON public.brands;
CREATE POLICY "Public can view brands" ON public.brands FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public can view categories" ON public.categories;
CREATE POLICY "Public can view categories" ON public.categories FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public can view banners" ON public.banners;
CREATE POLICY "Public can view banners" ON public.banners FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public can view branches" ON public.branches;
CREATE POLICY "Public can view branches" ON public.branches FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public can view promotions" ON public.promotions;
CREATE POLICY "Public can view promotions" ON public.promotions FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public can view store settings" ON public.store_settings;
CREATE POLICY "Public can view store settings" ON public.store_settings FOR SELECT USING (true);

-- Public can insert new orders
DROP POLICY IF EXISTS "Public can insert orders" ON public.orders;
CREATE POLICY "Public can insert orders" ON public.orders FOR INSERT WITH CHECK (true);

-- Authenticated admins have full management access
DROP POLICY IF EXISTS "Admins full access cameras" ON public.cameras;
CREATE POLICY "Admins full access cameras" ON public.cameras FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Admins full access camera_variants" ON public.camera_variants;
CREATE POLICY "Admins full access camera_variants" ON public.camera_variants FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Admins full access brands" ON public.brands;
CREATE POLICY "Admins full access brands" ON public.brands FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Admins full access categories" ON public.categories;
CREATE POLICY "Admins full access categories" ON public.categories FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Admins full access banners" ON public.banners;
CREATE POLICY "Admins full access banners" ON public.banners FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Admins full access orders" ON public.orders;
CREATE POLICY "Admins full access orders" ON public.orders FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Admins full access branches" ON public.branches;
CREATE POLICY "Admins full access branches" ON public.branches FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Admins full access promotions" ON public.promotions;
CREATE POLICY "Admins full access promotions" ON public.promotions FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Admins full access store_settings" ON public.store_settings;
CREATE POLICY "Admins full access store_settings" ON public.store_settings FOR ALL TO authenticated USING (true) WITH CHECK (true);
