"use client";

import { useEffect, useState, use } from "react";
import { supabase } from "../../../../lib/supabase";
import { Button } from "../../../../components/ui/button";
import { Input } from "../../../../components/ui/input";
import { Label } from "../../../../components/ui/label";
import { CreatableSelect } from "../../../../components/ui/creatable-select";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
  DialogTrigger,
} from "../../../../components/ui/dialog";
import { Loader2, ArrowLeft, Plus, Trash2 } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";

export default function EditCameraPage({ params }) {
  const resolvedParams = use(params);
  const id = resolvedParams.id;

  const router = useRouter();
  const [loading, setLoading] = useState(true);
  const [camera, setCamera] = useState(null);
  const [variants, setVariants] = useState([]);

  // Option Lists
  const [brands, setBrands] = useState([]);
  const [categories, setCategories] = useState([]);
  const [series, setSeries] = useState([]);
  const [conditions, setConditions] = useState([]);
  const [colors, setColors] = useState([]);

  // Form State for main camera
  const [formData, setFormData] = useState({
    name: "",
    image: "",
    brand_id: "",
    category_id: "",
    series_id: "",
  });

  // New Variant State
  const [isVariantOpen, setIsVariantOpen] = useState(false);
  const [newVariant, setNewVariant] = useState({
    condition_id: "",
    color_id: "",
    price: "",
    in_stock: true,
  });

  useEffect(() => {
    fetchOptions();
    if (id && id !== "new") fetchCamera();
    else if (id === "new") {
      setLoading(false);
      setCamera({ name: "New Camera" }); // Placeholder
    }
  }, [id]);

  const fetchOptions = async () => {
    const fetchData = async (table) => {
      const { data } = await supabase.from(table).select("*").order("name");
      return (data || []).map((item) => ({
        value: item.id.toString(),
        label: item.name,
      }));
    };

    const [b, c, s, cond, col] = await Promise.all([
      fetchData("brands"),
      fetchData("categories"),
      fetchData("series"),
      fetchData("conditions"),
      fetchData("colors"),
    ]);

    setBrands(b);
    setCategories(c);
    setSeries(s);
    setConditions(cond);
    setColors(col);
  };

  const fetchCamera = async () => {
    setLoading(true);
    // 1. Fetch Camera
    const { data: camData, error: camError } = await supabase
      .from("cameras")
      .select("*")
      .eq("id", id)
      .single();

    if (camError) {
      console.error(camError);
    } else {
      setCamera(camData);
      setFormData({
        name: camData.name,
        image: camData.image || "",
        brand_id: camData.brand_id?.toString() || "",
        category_id: camData.category_id?.toString() || "",
        series_id: camData.series_id?.toString() || "",
      });
    }

    // 2. Fetch Variants
    const { data: varData } = await supabase
      .from("camera_variants")
      .select(`*, condition:conditions(name), color:colors(name)`)
      .eq("camera_id", id);

    setVariants(varData || []);
    setLoading(false);
  };

  // --- Create Handlers ---

  const handleCreateOption = async (table, name, setter) => {
    const { data, error } = await supabase
      .from(table)
      .insert([{ name }])
      .select()
      .single();
    if (error) {
      alert(`Error creating ${table}: ` + error.message);
      return null;
    }
    const newOption = { value: data.id.toString(), label: data.name };
    setter((prev) =>
      [...prev, newOption].sort((a, b) => a.label.localeCompare(b.label)),
    );
    return data.id.toString();
  };

  // --- Main Save Handler ---

  const handleSaveCamera = async () => {
    if (!formData.name) return alert("Name is required");

    // Generate a numeric ID if new (simple random for now, or let DB handle if identity)
    // Schema says 'id' is bigint PRIMARY KEY (not identity?), wait Schema says:
    // id bigint PRIMARY KEY (Ref 47). It seems NOT generated by default?
    // Step 5 schema: id bigint PRIMARY KEY.
    // We should probably change it to IDENTITY or generate a random one here.
    // Let's generate a random ID for "new" if it's primary key without default.

    const payload = {
      name: formData.name,
      image: formData.image,
      brand_id: formData.brand_id || null,
      category_id: formData.category_id || null,
      series_id: formData.series_id || null,
    };

    let error;
    let newId = id;

    if (id === "new") {
      const randomId = Math.floor(Math.random() * 1000000);
      const { error: insertError } = await supabase
        .from("cameras")
        .insert([{ ...payload, id: randomId }]);
      error = insertError;
      newId = randomId;
    } else {
      const { error: updateError } = await supabase
        .from("cameras")
        .update(payload)
        .eq("id", id);
      error = updateError;
    }

    if (error) alert("Error saving: " + error.message);
    else {
      alert("Saved successfully!");
      if (id === "new") router.push(`/admin/cameras/${newId}`);
    }
  };

  const handleAddVariant = async () => {
    if (!newVariant.condition_id || !newVariant.color_id || !newVariant.price) {
      alert("Please fill all fields");
      return;
    }

    if (id === "new") {
      alert("Please save the camera first before adding variants.");
      return;
    }

    const { error } = await supabase.from("camera_variants").insert([
      {
        camera_id: id,
        condition_id: newVariant.condition_id,
        color_id: newVariant.color_id,
        price: parseFloat(newVariant.price),
        in_stock: newVariant.in_stock,
      },
    ]);

    if (error) {
      alert("Error adding variant: " + error.message);
    } else {
      setIsVariantOpen(false);
      setNewVariant({
        condition_id: "",
        color_id: "",
        price: "",
        in_stock: true,
      });
      fetchCamera();
    }
  };

  const handleDeleteVariant = async (variantId) => {
    if (!confirm("Delete this variant?")) return;
    const { error } = await supabase
      .from("camera_variants")
      .delete()
      .eq("id", variantId);
    if (error) alert("Error: " + error.message);
    else fetchCamera();
  };

  if (loading)
    return (
      <div className="flex justify-center p-8">
        <Loader2 className="animate-spin" />
      </div>
    );

  return (
    <div className="space-y-8 max-w-4xl mx-auto pb-20">
      <div className="flex items-center gap-4">
        <Link href="/admin/cameras">
          <Button variant="ghost" size="icon">
            <ArrowLeft className="w-4 h-4" />
          </Button>
        </Link>
        <h1 className="text-2xl font-black text-primary">
          {id === "new" ? "New Camera" : `Edit Camera: ${camera?.name}`}
        </h1>
      </div>

      {/* Main Info */}
      <div className="bg-card p-6 rounded-xl border space-y-4 shadow-sm">
        <h2 className="text-xl font-bold border-b pb-2">Basic Info</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="space-y-2">
            <Label>Camera Name</Label>
            <Input
              value={formData.name}
              onChange={(e) =>
                setFormData({ ...formData, name: e.target.value })
              }
            />
          </div>
          <div className="space-y-2">
            <Label>Image URL</Label>
            <div className="flex gap-2">
              <Input
                value={formData.image}
                onChange={(e) =>
                  setFormData({ ...formData, image: e.target.value })
                }
              />
              {formData.image && (
                <img
                  src={formData.image}
                  className="w-10 h-10 object-cover rounded bg-muted"
                />
              )}
            </div>
          </div>

          {/* Linked Data Selects */}
          <div className="space-y-2">
            <Label>Brand</Label>
            <CreatableSelect
              options={brands}
              value={formData.brand_id}
              onChange={(val) => setFormData({ ...formData, brand_id: val })}
              onCreate={async (name) => {
                const newId = await handleCreateOption(
                  "brands",
                  name,
                  setBrands,
                );
                if (newId)
                  setFormData((prev) => ({ ...prev, brand_id: newId }));
              }}
              placeholder="Select Brand..."
              createLabel="Create Brand"
            />
          </div>

          <div className="space-y-2">
            <Label>Series</Label>
            <CreatableSelect
              options={series}
              value={formData.series_id}
              onChange={(val) => setFormData({ ...formData, series_id: val })}
              onCreate={async (name) => {
                // For series we need brand_id constraint strictly speaking,
                // but for now simple insert is okay or we need to ask for brand
                const { data, error } = await supabase
                  .from("series")
                  .insert([
                    {
                      name,
                      brand_id: formData.brand_id || null, // Try to link if brand selected
                    },
                  ])
                  .select()
                  .single();
                if (error) return alert(error.message);
                const newOption = {
                  value: data.id.toString(),
                  label: data.name,
                };
                setSeries((prev) => [...prev, newOption]);
                setFormData((prev) => ({
                  ...prev,
                  series_id: data.id.toString(),
                }));
              }}
              placeholder="Select Series..."
              createLabel="Create Series"
            />
          </div>

          <div className="space-y-2">
            <Label>Category</Label>
            <CreatableSelect
              options={categories}
              value={formData.category_id}
              onChange={(val) => setFormData({ ...formData, category_id: val })}
              onCreate={async (name) => {
                const newId = await handleCreateOption(
                  "categories",
                  name,
                  setCategories,
                );
                if (newId)
                  setFormData((prev) => ({ ...prev, category_id: newId }));
              }}
              placeholder="Select Category..."
              createLabel="Create Category"
            />
          </div>
        </div>
        <div className="flex justify-end">
          <Button onClick={handleSaveCamera}>Save Changes</Button>
        </div>
      </div>

      {/* Variants (Only for existing cameras) */}
      {id !== "new" && (
        <div className="bg-card p-6 rounded-xl border space-y-4 shadow-sm">
          <div className="flex justify-between items-center border-b pb-2">
            <h2 className="text-xl font-bold">Variants (Prices & Stock)</h2>
            <Dialog open={isVariantOpen} onOpenChange={setIsVariantOpen}>
              <DialogTrigger asChild>
                <Button size="sm" variant="outline">
                  <Plus className="w-4 h-4 mr-2" /> Add Variant
                </Button>
              </DialogTrigger>
              <DialogContent>
                <DialogHeader>
                  <DialogTitle>Add New Variant</DialogTitle>
                </DialogHeader>
                <div className="space-y-4 py-4">
                  <div className="space-y-2">
                    <Label>Condition</Label>
                    <CreatableSelect
                      options={conditions}
                      value={newVariant.condition_id}
                      onChange={(val) =>
                        setNewVariant({ ...newVariant, condition_id: val })
                      }
                      onCreate={async (name) => {
                        const newId = await handleCreateOption(
                          "conditions",
                          name,
                          setConditions,
                        );
                        if (newId)
                          setNewVariant((prev) => ({
                            ...prev,
                            condition_id: newId,
                          }));
                      }}
                      placeholder="Select Condition..."
                      createLabel="Create Condition"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label>Color</Label>
                    <CreatableSelect
                      options={colors}
                      value={newVariant.color_id}
                      onChange={(val) =>
                        setNewVariant({ ...newVariant, color_id: val })
                      }
                      onCreate={async (name) => {
                        // Colors usually need hex code too, we'll just insert name for now
                        const newId = await handleCreateOption(
                          "colors",
                          name,
                          setColors,
                        );
                        if (newId)
                          setNewVariant((prev) => ({
                            ...prev,
                            color_id: newId,
                          }));
                      }}
                      placeholder="Select Color..."
                      createLabel="Create Color"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label>Price (VND)</Label>
                    <Input
                      type="number"
                      placeholder="e.g. 5000000"
                      onChange={(e) =>
                        setNewVariant({ ...newVariant, price: e.target.value })
                      }
                    />
                  </div>
                </div>
                <DialogFooter>
                  <Button onClick={handleAddVariant}>Create Variant</Button>
                </DialogFooter>
              </DialogContent>
            </Dialog>
          </div>

          <div className="space-y-2">
            {variants.map((variant) => (
              <div
                key={variant.id}
                className="flex items-center justify-between p-3 bg-muted/20 rounded-lg border"
              >
                <div>
                  <div className="font-bold flex gap-2">
                    <span>
                      {variant.condition?.name || "Unknown Condition"}
                    </span>
                    <span>•</span>
                    <span>{variant.color?.name || "Unknown Color"}</span>
                  </div>
                  <div className="text-sm text-muted-foreground">
                    Price:{" "}
                    {new Intl.NumberFormat("vi-VN").format(variant.price)}đ
                  </div>
                </div>
                <Button
                  variant="ghost"
                  size="icon"
                  className="text-destructive hover:text-destructive hover:bg-destructive/10"
                  onClick={() => handleDeleteVariant(variant.id)}
                >
                  <Trash2 className="w-4 h-4" />
                </Button>
              </div>
            ))}
            {variants.length === 0 && (
              <div className="text-muted-foreground text-center py-4">
                No variants found.
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
